# Generated by Django 5.1.3 on 2024-11-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('mail', models.EmailField(max_length=254, verbose_name='Почта')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
