# Generated by Django 5.1.3 on 2024-12-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
